version: "3"

services:
  wppconnect:
    build:
      context: .
    environment:
      - PORT=${PORT}
      - DEPLOYMENT_NUMBER=${DEPLOYMENT_NUMBER}
    volumes:
      - ./wppconnect_tokens/server-${DEPLOYMENT_NUMBER}:/usr/src/wpp-server/tokens
    ports:
      - "${PORT}:${PORT}"

volumes:
  wppconnect_tokens: {}      